"""added user column to Order

Revision ID: 3958bc7fe7a4
Revises: f6e53a458a53
Create Date: 2022-04-26 10:18:32.348848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3958bc7fe7a4'
down_revision = 'f6e53a458a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'user')
    # ### end Alembic commands ###
