"""added columns

Revision ID: 54efebd6fdb6
Revises: c635c1a15faa
Create Date: 2022-04-12 17:41:47.884594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54efebd6fdb6'
down_revision = 'c635c1a15faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foto', sa.Column('country', sa.String(length=80), nullable=True))
    op.add_column('foto', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('foto', sa.Column('desctiption', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foto', 'desctiption')
    op.drop_column('foto', 'city')
    op.drop_column('foto', 'country')
    # ### end Alembic commands ###
