"""deleted the mapper model

Revision ID: 6c9c7cb0bd66
Revises: 923cb819ea49
Create Date: 2022-04-13 13:24:33.943859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9c7cb0bd66'
down_revision = '923cb819ea49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foto_order')
    op.drop_column('foto', 'desctiption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foto', sa.Column('desctiption', sa.VARCHAR(length=1000), nullable=True))
    op.create_table('foto_order',
    sa.Column('foto_id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('number_of_fotos', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['foto_id'], ['foto.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('foto_id', 'order_id')
    )
    # ### end Alembic commands ###
