"""add picture_url to Cookie

Revision ID: 7182805632df
Revises: 9261c9b1d9cb
Create Date: 2022-03-28 14:49:51.422190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7182805632df'
down_revision = '9261c9b1d9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foto', sa.Column('picture_url', sa.String(length=260), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foto', 'picture_url')
    # ### end Alembic commands ###
