"""rearanged order and address relationship

Revision ID: aebb066f0f11
Revises: 6c9c7cb0bd66
Create Date: 2022-04-14 17:20:15.063382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aebb066f0f11'
down_revision = '6c9c7cb0bd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'order_id')
    op.add_column('order', sa.Column('adress_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order', 'address', ['adress_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'adress_id')
    op.add_column('address', sa.Column('order_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'address', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###
