"""deleted name column from address

Revision ID: c2853c346820
Revises: 0047a604b481
Create Date: 2022-04-19 10:53:39.325109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2853c346820'
down_revision = '0047a604b481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('name', sa.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
