"""test

Revision ID: c49349b36fd2
Revises: f02c3bf8ccc0
Create Date: 2022-04-04 18:08:31.139604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49349b36fd2'
down_revision = 'f02c3bf8ccc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foto_order',
    sa.Column('foto_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('number_of_fotos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foto_id'], ['foto.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('foto_id', 'order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foto_order')
    # ### end Alembic commands ###
