"""first migration

Revision ID: c635c1a15faa
Revises: 
Create Date: 2022-04-12 17:11:29.201132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c635c1a15faa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foto',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('picture_url', sa.String(length=80), nullable=True),
    sa.Column('genre', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('picture_url'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foto')
    # ### end Alembic commands ###
